<?php $this->headLink()->appendStylesheet('/resources/js/chosen/chosen.css'); ?>
<?php $this->headScript()->appendFile($this->baseUrl('/resources/js/chosen/chosen.jquery.min.js')); ?>
<?php $this->headScript()->appendFile($this->baseUrl('/resources/js/chosen/ajax-chosen.min.js')); ?>
<?php $this->headLink()->appendStylesheet('/vendors/jquery/css/ui-lightness/jquery-ui-1.8.21.custom.css'); ?>
<?php $this->headScript()->appendFile($this->baseUrl('/vendors/jquery/js/jquery-ui-1.8.21.custom.min.js')); ?>

<script type="text/javascript">
    $(function(){

        $("#mla_id").chosen({width : '400px;' });
        $("#mla_id").ajaxChosen({
            type: 'GET',
            url: "/system/mla/getmla/format/json",
            afterTypeDelay : 0,
            minTermLength : 1,
            dataType: 'json'
        }, function (data) {
            var results = [];
	
            $.each(data, function (i, val) {
                results.push({ value: val.mla_id, text: val.mla_firstname+' '+val.mla_lastname+" ("+val.state_name+" , "+val.name+" )" });
            });
	
            return results;
        });
        
        $('body').on('click', 'a.ajax', function(e){
            e.preventDefault();

            var title = $(this).attr('title');
            var remote = $(this).attr('href');
          
            Layout.alert(title, remote);
        });  

        Layout = {};
        Layout.alert = function (title, content){
            $modalTitle = $('<b>').text(title);
            $modalDismiss = $('<span class="close" data-dismiss="modal">').html('&times;');
            $modal = $('<div class="modal">');
            $modalHeader = $('<div class="modal-header">').append($modalTitle).append($modalDismiss);
            $modalBody = $('<div class="modal-body">');//.append(content);
            $modal.append($modalHeader)
            .append($modalBody).modal({
                remote: content
            })
            return;
        }
        
    });
</script>
<section id="content">
    <div class="container marg-top">
        <div class="row-fluid">
            <!-- Tab -->
            <div class="page">       <h4 class="black"><i class="icon-user"></i> Attach Mla <?php if ($this->mlo !== null) {
    echo "to ". $this->mlo->mlo_name . ' ( ' . $this->mlo->state_name . " " . $this->mlo->name . " )";
} ?> Motor Licensing office </h4>
                <a title="MLA Information" class="ajax"  href="/system/mla/view/id/<?php echo $this->mla->mla_id; ?>">View current Mla</a> <br/><br/>
<?php echo $this->form; ?>
            </div>
        </div>
</section>