<br/>
<style>
    label {
        display: inline-block;
    }
</style>
<form method="<?php echo $this->element->getMethod(); ?>" action="<?php echo $this->element->getAction() ?>">
    <table>
        <tr>
            <td><h3>Charge</h3></td><td>: <?php echo $this->element->charge_name->getValue(); ?><?php echo $this->element->charge_name; ?><?php echo $this->element->charge_id; ?></td>
        </tr>
        <tr>
            <td><label>Flat fee :</label> </td><td> <?php echo $this->element->flatfee; ?></td>
        </tr>
    </table>  
    <?php echo $this->element->getSubForm('settings'); ?> 
    <table>
        <tr><td> <?php echo $this->element->sub; ?> </td></tr>
    </table>   
</form>