<?php $this->headScript()->appendFile($this->baseUrl('/vendors/DataTables/media/js/jquery.dataTables.js')); ?>
<script type="text/javascript">
    $(function(){
        var oTable3 = $('table#datatable3').dataTable({
            "sDom": '<T>tir<p>',
            'iDisplayLength':<?php echo $this->items->getDefaultDisplayLength(); ?>,
            'iDeferLoading':<?php echo $this->items->getTotal(); ?>,
            'bProcessing':true,
            'bServerSide':true,
            'sAjaxSource':'<?php echo $this->baseUrl('/default/charges/vehiclecharges/id/' . $this->id . '/format/json'); ?>',
            'aoColumnDefs' : [
                {'bSortable': false, 'aTargets': [0]}
            ],
           
            'fnServerParams': function(aoData){
                var sSearch = $('#table-search3').val();
                aoData.push(  {
                    "name": "sSearch", 
                    "value":  sSearch
                } );
               
                
                return aoData;
            }            
        })    
        $( "#table-search3" ).keyup( function () {
            oTable3.fnDraw();
        } );
       
        
        
        
        $("#resetFilter").click(function(e){
            e.preventDefault();
            $("#table-search").val("");
            $("#order-status").val("");
            oTable3.fnDraw();
        })
        
        $("#resetDateranges").click(function(e){
            e.preventDefault();
            $("#order-date").val("");
            $("#end-order-date").val("");
            oTable3.fnDraw();
        })
        
        //process renewal of charges
        $(".processRenewal").click(function(e){
            e.preventDefault(); 
            var checkedInputs = 0;
            $("input.check-item").each(function(){
                if($(this).is(":checked")){
                    checkedInputs += 1;
                }   
            });
            if(checkedInputs == 0){
                alert("Select at least one charge to renew")
            }
            else {
                //$('form#itemList').submit
                var dataString = $('form#itemList').serialize();
                //empty dialog
               
                $.ajax({
                    type : "POST",
                    data : dataString,
                    dataType : 'json',
                    url : "/default/vehicles/renew/format/json",
                    timeout : 100000,
                    beforeSend : function(){
                        //append ajax processing
                        $('.processRenewal').button('loading');
                    },
                    error : function(){
                        alert("An error occured while making this request");
                    },
                    success : function(data){
                        if(data.status ==  1){
                            //remove previous success message if any exist
                            $("#renewalsuccess").remove();
                            //open the first tab
                            $('#myTab a:first').tab('show'); // Select first tab
                            //display appropriate message
                            $("<div />")
                            .attr('id','renewalsuccess')
                            .attr('class','displayElement alert alert-success')
                            .css('display','block')
                            .html("<b>The selected documents were renewed successfully</b> ")
                            .prependTo("#mvbalance");
                            $('.processRenewal').button('reset');
                            //programmatically reload datatables to reflect the change
                            //oTable3.fnDraw();
                        }  else{
                            //alert(data.message);
                        }
                       
                    },
                    complete : function(){
         
                    }
                });  
                
                //    }
            }
        });
        //process fund mvcard action()
        $("#sub").live('click',function(e){
            e.preventDefault();
            var dataString = $("#mvcardfundForm").serialize();
            $.ajax({
                type : "POST",
                data : dataString,
                dataType : 'json',
                url : "/default/vehicles/fundmv/format/json",
                timeout : 60000,
                beforeSend : function(){
                    //append ajax processing
                    $("#mvcardfundForm").remove();
                    $("<div />").html("<b>Processing...</b>").appendTo("#fundmvcard");
                },
                error : function(){
                    alert("An error occured while making this request");
                },
                success : function(data){
                    $("#fundmvcard").empty();
                    if(data.status ==  1){
                        //trigger change of tab 1 programmatically
                        $('.renewcharge').click();
                        $("<div />").html("<span class='alert alert-success' style='display:inline-block'><b>Mvreg card successfully funded</b></span>").appendTo("#fundmvcard");
                        $("#fundmvcard").append(data.form);   
                    }  else{
                        $("#fundmvcard").append(data.form);   
                    }
                       
                },
                complete : function(){
                    //remove link to supercard balance as it does not function on this page
                    $("#scardbalance").remove();
                }
            });  
        });
        //close renewcharge modal
        $("#closeModal").click(function(e){
            e.preventDefault();
            $("#myModal").modal("hide");
        })
        
        //remove check balance link for super card
        $("#scardbalance").remove();
        //renew selected vehicle charges
        $('.renewcharge').live('click', function(e){
            e.preventDefault();
            var checkedInputs = 0;
            $("input.check-item").each(function(){
                if($(this).is(":checked")){
                    checkedInputs += 1;
                }   
            });
            if(checkedInputs == 0){
                alert("Select at least one charge to renew")
            }
            else {
                //if(confirm("are you sure you want to renew the selected charges ?")){
                //$('form#itemList').submit
                var dataString = $('form#itemList').serialize();
                //empty dialog
                //$(".renewchargescontainer").empty();
                $("#mvbalance").empty();
                //hide all tabs 
                $(".renewchargescontainer").hide();
                //show ajax loader message
                $(".renewchargesLoader").show();
                //open dialog
                $("#myModal").modal('show');
                $.ajax({
                    type : "POST",
                    data : dataString,
                    dataType : 'json',
                    url : "/default/vehicles/estimate/format/json",
                    timeout : 60000,
                    beforeSend : function(){
                        //append ajax processing
                        
                    },
                    error : function(){
                        alert("An error occured while making this request");
                    },
                    success : function(data){
                        $(".renewchargesLoader").hide();
                        $(".renewchargescontainer").show();
                        if(data.status ==  1){
                            $("<div />")
                            .attr('class','displayElement')
                            .css('display','block')
                            .html("<b>Total Cost :</b> "+data.total+'<br/>')
                            .append("<b>Mvregno :</b> "+data.mvregno+'<br/>')
                            .append("<b>Mvreg balance :</b> "+data.creditbalance+'<br/>')
                            .appendTo("#mvbalance");
                                
                               
                        }  else{
                            alert(data.message);
                        }
                       
                    },
                    complete : function(){
         
                    }
                });  
                
                //    }
            }
        }) ;  
        
        $('input.check-ctrl').live('click', function(e){
            if($(this).is(":checked")){
                $('.check-item').attr("checked",true);
            }
            else{
                $('.check-item').attr("checked",false);
            }
        }) ;
    
        $('input.check-item').click(function(e){
            //alert('yes');
            if(!$(this).is(":checked")){
                $('.check-ctrl').attr("checked",false);
            }
        }) ;
 
        //click button
        $('a.removeItem3').live('click', function(e){
            e.preventDefault();
            var  url = $(this).attr('href');
            if(confirm("do you want to remove this Items ?")){
                window.location.href = url;
            }
        }) ;  
        
        //group actions
        //delete single item
        $('#delete-all').live('click', function(e){
            e.preventDefault();
            var checkedInputs = 0;
            $("input.check-item3").each(function(){
                if($(this).is(":checked")){
                    checkedInputs += 1;
                }   
            });
            if(checkedInputs == 0){
                alert("check at least one row")
            }
            else {
                if(confirm("are you sure you want to remove all ?")){
                    //$('form#itemList3').submit();
                    
                }
            }
        }) ;  
        
        $('input#sub-btn3').click(function(e){
            //  alert('here');
            e.preventDefault();
            var checkedInputs = 0;
            $("form#group-id input3").each(function(){
                if($(this).is(":checked")){
                    checkedInputs += 1;
                }   
            });
            if(checkedInputs == 0){
                alert("check at least one row to proceed")
            }
            else {
                // alert('checked is '+checkedInputs)
                $('form#group-id3').submit();
            }
     
        }) ;  


    });
</script>
<style type="text/css">
    form#searchbox {
        margin: 0 0 5px 0;
        display: inline-block;

    }
</style>


<!-- Tab -->
<h3><i classs="icon-user"></i> Charge(s)</h3>
<?php if ($this->items->fetchAll()->count() == 0) : ?>
    <div class="alert-info">There are no charges set up </div> <br/>
    <!--<div class="alert-info">Click <a class="btn" href="/space/rooms/add"><b>Here</b></a> to add  a new charge</div> -->
<?php else : ?>
    <div>
        <a href="/default/profile/add/id/<?php echo $this->id; ?>" class="btn renewcharge" title="new charge">Renew selected</a>&nbsp;&nbsp;&nbsp;
    </div>

    <br/>
    <div id="searchId3" >
        <div id="searchclass3">
            <form id="searchbox3" action="">
                <input name="table-search" id="table-search3" type="text" placeholder="Search here">
            </form>
        </div>
    </div>
    <?php $messages = $this->flashMessenger('warning', '<li class="alert alert-%s">%s</li>'); ?>
    <?php if ($messages): ?>
        <ul class="messages">
            <?php echo $messages; ?>
        </ul> 
    <?php endif; ?>

    <form id="itemList" action="/default/vehicles/deleteall/" method="post">
        <input type="hidden" name="vehicle_id" value="<?php echo $this->id; ?>" />
        <table id="datatable3" class="table table-striped table-bordered table-condensed" >
            <thead>
                <tr>
                    <th> <input type="checkbox" name="checkctrl" class="check-ctrl" />  </th> 
                    <th><a class="tblCaption" href="#"><?php echo 'Vehicle Model'; ?></a></th>
                    <th><a class="tblCaption" href="#"><?php echo 'Charge Title'; ?></a></th>
                    <th><a class="tblCaption" href="#"><?php echo 'Status'; ?></a></th>
                    <th><a class="tblCaption" href="#"><?php echo 'Payment Amount'; ?></a></th>
                    <th><a class="tblCaption" href="#"><?php echo 'Expiry date'; ?></a></th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->items->fetchAll() as $item) { ?>
                    <?php
                    $status = "";
                    if ($item->payment_expiry == "") {
                        $status = "Expired";
                        $stateCtrl = 0;
                    } else if ($item->payment_expiry != "") {
                        $currentDate = strtotime(date("Y-d-m"));
                        $expiryDate = strtotime($item->payment_expiry);
                        if ($expiryDate > $currentDate) {
                            $status = "Expired";
                            $stateCtrl = 0;
                        } else {
                            $status = "Active";
                            $stateCtrl = 1;
                        }
                    }
                    ?>
                    <tr>
                        <?php $documentValue = $item->vehicle_id . "P" . $item->charge_id; ?>
                        <td><input type="checkbox" name="itemid[]" class="check-item" value="<?php echo $documentValue; ?>"/></td>
                        <td><?php echo $item->vehicle_model; ?></td>
                        <td><?php echo $item->charge_title; ?></td>
                        <td><?php echo $status; ?></td>
                        <td><?php echo $item->payment_amount; ?> </td>
                        <td><?php echo $item->payment_expiry; ?> </td>
                        <td>&nbsp;<a href="/default/profiles/view/id/<?php echo $item->vehicle_id; ?>/charge/<?php echo $item->charge_id; ?>">Renew</a>&nbsp;&nbsp;</td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </form>
<?php endif; ?>
<div class="modal hide" id="myModal">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">X</button>
        <h3>Renew Charges</h3>
    </div>
    <div class="modal-body">
        <div class="renewchargesLoader">Please wait...</div>   
        <div class="renewchargescontainer">
            <ul id="myTab" class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#mvbalance">Balance</a></li>
                <li><a data-toggle="tab" href="#fundmvcard">Fund mvcard</a></li>
            </ul>
            <div class="tab-content" style="width: auto; overflow: auto;">
                <div id="mvbalance" class="tab-pane active"> </div>
                <div id="fundmvcard" class="tab-pane"><?php echo $this->mvcardFundForm; ?> </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <a href="#" id="closeModal" class="btn">Close</a>
        <a href="#" data-loading-text="Processing renewal..." class="btn btn-primary processRenewal">Continue renewal</a>
    </div>
</div>