<?php //$this->headLink()->prependStylesheet('/resources/css/config.css');    ?>
<?php ///$this->headLink()->prependStylesheet('/resources/css/paginate.css');    ?>
<?php //$this->headLink()->prependStylesheet('/resources/css/info.css');    ?>
<?php //$this->headScript()->appendFile($this->baseUrl('/resources/vendors/jquery/js/jquery-1.7.2.min.js'));    ?>
<?php //$this->headScript()->appendFile($this->baseUrl('/resources/vendors/DataTables/media/js/jquery.dataTables.js'));    ?>
<script type="text/javascript">
    $(function(){
        
        $("#state").live('change',function(e){
            e.preventDefault();
        
            var currentState = $("#state").val();
            if(currentState == ""){
         
            }else{
                $.ajax({
                    type : "POST",
                    data : {
                        state : currentState
                    },
                    dataType : 'json',
                    url : "/default/profiles/states/format/json",
                    timeout : 60000,
                    beforeSend : function(){
                        //append ajax processing
                        $("<option >")
                        .text("Please wait ...")
                        .attr("selected",true)
                        .attr("id", 'ajaxloader')
                        .appendTo("#state");
                        
                          $("<option >")
                        .text("Fetching options ...")
                        .attr("selected",true)
                        .attr("id", 'lgaloader')
                        .appendTo("#lga");
                    },
                    error : function(){
                    
                    },
                    success : function(data){
                       $("#ajaxloader").remove();
                        $("#lgaloader").remove();
                        
                       $("#state").val(currentState);
                       
                       $("#lga").empty();
                       $("<option />").text("Select").val("").appendTo("#lga");
                        
                       $.each(data.ret, function(i,v){
                           $("<option />").text(v.name).val(v.id).appendTo("#lga");
                       });
                       
                    },
                    complete : function(){
         
                    }
                });  
            }
        })
    
    });
</script>
<br/>
<h3 class="black"><i class="icon-user"></i> Customers Profile</h3>
<div class="tabbable tabs-left">
    <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#lA">Profile</a></li>
        <li><a data-toggle="tab" href="#lB">Vehicles</a></li>
        <li><a data-toggle="tab" href="#lC">Charges</a></li>
        <li><a data-toggle="tab" href="#lD">Funding</a></li>
    </ul>
    <div class="tab-content" style="width: auto; overflow: auto;">
        <div id="lA" class="tab-pane active">
            <?php // echo $this->additem; 
            if($this->customer === null){
           echo $this->action('add', 'profiles', 'default', array('id' => $this->id)); 
            }else {
                echo $this->action('edit', 'profiles', 'default', array('id' => $this->id));
            }
           ?>
        </div>
        <div id="lB" class="tab-pane">
          <?php  echo $this->action('vehicles', 'profiles', 'default', array('id' => $this->id)); ?>
        </div>
        <div id="lC" class="tab-pane">
            dddd
        </div>
        <div id="lD" class="tab-pane">
            dddd
        </div>
    </div>
</div>

