<?php $this->headScript()->appendFile($this->baseUrl('/vendors/DataTables/media/js/jquery.dataTables.js')); ?>
<script type="text/javascript">
    $(function() {
        var oTable = $('#datatable').dataTable({
            "sDom":"<'row-fluid'<'pull-left'i><'pull-right'f>><t>",
            "iDisplayLength":200,
            "bProcessing":false
        });
    });
</script>

<?php $this->title = "System Resources"; ?>

<div class="page-header position-relative">
    <h1>
        <?php echo $this->title; ?>
    </h1>
</div>
<div>
    <a class="btn btn-small btn-success" title="Rebuild the Access Control List" href="<?php echo $this->url(array('action' => 'build')); ?>"><i class="icon-file"></i> Rebuild Resource List</a>	
</div>
<br/>
<table id="datatable" class="table table-striped table-condensed">
    <thead>
        <tr>
            <th>Resource</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->resources as $resource) : ?>
            <tr>
                <td><?php echo $resource->id ?></td>
                <td><a href="<?php echo $this->url(array('action' => 'permissions', 'id' => $resource->id)) ?>" class="btn btn-mini toggle-row pull-right btn-primary">Permissions</a></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
