<?php $this->headScript()->appendFile($this->baseUrl('/vendors/DataTables/media/js/jquery.dataTables.js')); ?>
<style type="text/css">
    /* Start by setting display:none to make this hidden.
   Then we position it in relation to the viewport window
   with position:fixed. Width, height, top and left speak
   speak for themselves. Background we set to 80% white with
   our animation centered, and no-repeating */
    .modalm {
        display:    none;
        position:   fixed;
        z-index:    1000;
        top:        0;
        left:       0;
        height:     100%;
        width:      100%;
        background: rgba( 255, 255, 255, .8 ) 
            url('/resources/img/ajaxloader.gif')
            50% 50% 
            no-repeat;
    }

    /* When the body has the loading class, we turn
       the scrollbar off with overflow:hidden */
    body.loading {
        overflow: hidden;   
    }

    /* Anytime the body has the loading class, our
       modal element will be visible */
    body.loading .modalm {
        display: block;
    }
</style>
<script type="text/javascript">
    $(function(){
        var oTable = $('table#datatable').dataTable({
            "sDom": '<T>tir<p>',
            'iDisplayLength':<?php echo $this->items->getDefaultDisplayLength(); ?>,
            'iDeferLoading':<?php echo $this->items->getTotal(); ?>,
            'bProcessing':true,
            'bServerSide':true,
            'sAjaxSource':'<?php echo $this->baseUrl('/system/staff/index/format/json'); ?>',
            'aoColumnDefs' : [
                {'bSortable': false, 'aTargets': [0]}
            ],
           
            'fnServerParams': function(aoData){
                var sSearch = $('#table-search2').val();
                aoData.push(  {
                    "name": "sSearch", 
                    "value":  sSearch
                } );
               
                
                return aoData;
            }            
        })    
        $( "#table-search2" ).keyup( function () {
            oTable.fnDraw();
        } );
       
        
        
          $('.statustoggle').live('click', function(e){
            e.preventDefault();
            var checkedInputs = 0;
            $("input.check-item").each(function(){
                if($(this).is(":checked")){
                    checkedInputs += 1;
                }   
            });
            
            if(checkedInputs == 0){
                alert("select at least one role")
            }
            else {
                if(confirm("do you want to enable the selected user(s)?")){
                    var dataString = $("#itemList").serialize();
                    var desiredState = $(this).attr("id");
                    dataString += "&dstatus="+desiredState;
                   // alert(dataString);
                  //  alert(desiredState);
                    $.ajax({
                        type : "POST",
                        data : dataString,
                        dataType : 'json',
                        url : "/system/staff/itemstatus/format/json",
                        timeout : 60000,
                        beforeSend : function(){
                        },
                        error : function(){
                            alert("There was an error processing the request. Please contact admin");
                        },
                        success : function(data){
                            // $('#estimateResult').fadeIn('slow');
                            alert("Update successful");
                        },
                        complete : function(){
                                oTable.fnDraw();
                        }
                    });  
                }
            }
        }) ;  
        
        
        $("#resetFilter").click(function(e){
            e.preventDefault();
            $("#table-search").val("");
            $("#order-status").val("");
            oTable.fnDraw();
        })
        
        $("#resetDateranges").click(function(e){
            e.preventDefault();
            $("#order-date").val("");
            $("#end-order-date").val("");
            oTable.fnDraw();
        })
        
        
        $('input.check-ctrl').live('click', function(e){
            if($(this).is(":checked")){
                $('.check-item').attr("checked",true);
            }
            else{
                $('.check-item').attr("checked",false);
            }
        }) ;
    
        $('input.check-item').click(function(e){
            //alert('yes');
            if(!$(this).is(":checked")){
                $('.check-ctrl').attr("checked",false);
            }
        }) ;
 
        //click button
        $('a.removeItem').live('click', function(e){
            e.preventDefault();
            var  url = $(this).attr('href');
            if(confirm("do you want to remove this Item ?")){
                window.location.href = url;
            }
        }) ;  
        
        //group actions
        //delete single item
        $('#delete-all').live('click', function(e){
            e.preventDefault();
            var checkedInputs = 0;
            $("input.check-item").each(function(){
                if($(this).is(":checked")){
                    checkedInputs += 1;
                }   
            });
            
            if(checkedInputs == 0){
                alert("select at least one row")
            }
            else {
                if(confirm("are you sure you want to remove the selected item(s)?")){
                    $('form#itemList').submit();
                }
            }
        }) ;  
        
        $('input#sub-btn').click(function(e){
            //  alert('here');
            e.preventDefault();
            var checkedInputs = 0;
            $("form#group-id input").each(function(){
                if($(this).is(":checked")){
                    checkedInputs += 1;
                }   
            });
            if(checkedInputs == 0){
                alert("check at least one row to proceed")
            }
            else {
                // alert('checked is '+checkedInputs)
                $('form#group-id').submit();
            }
     
        }) ;  

 //ajax loader for all ajax request
        $("body").on({
            ajaxStart: function() { 
                $(this).addClass("loading"); 
            },
            ajaxStop: function() { 
                $(this).removeClass("loading"); 
            }    
        });

    });
</script>
<style type="text/css">
    form#searchbox {
        margin: 0 0 5px 0;
        display: inline-block;

    }
</style>
<section id="content">
    <div class="container marg-top">
        <div class="row-fluid">
            <!-- Tab -->
            <div class="page">  
                <h3><i classs="icon-user"></i> <?php echo $this->itemName; ?></h3>
                <?php if ($this->items->fetchAll()->count() == 0) : ?>
                    <div class="alert-info">There are no <?php echo $this->itemName; ?>s currently set up </div> <br/>
                    <div class="alert-info">Click <a class="btn" href="/system/staff/add"><b>Here</b></a> to set up  a new <?php echo $this->itemName; ?></div>
                <?php else : ?>
                    <div>
                        <a  href="/system/staff/add" class="btn btn-mini" title="new Staff">New <?php echo $this->itemName; ?></a>&nbsp;&nbsp;&nbsp;
                        <a href="#" id="delete-all" class="btn btn-mini">Remove selected</a>
                         <a href="#" id="1"  class="statustoggle btn btn-success btn-mini">Enable selected</a>
                        <a href="#" id="0"  class="statustoggle btn btn-danger btn-mini">Disable selected</a>

                    </div>
                    <?php $this->title = $this->itemName; ?>
                    <br/>
                    <div id="searchId" >
                        <div id="searchclass2">
                            <form id="searchbox2" action="">
                                <input name="table-search" id="table-search2" type="text" placeholder="Search here">
                            </form>
                        </div>
                    </div>


                    <form id="itemList" action="/system/staff/deleteall/" method="post">
                        <table id="datatable" class="table table-striped table-bordered table-condensed" >
                            <thead>
                                <tr>
                                    <th><a class="tblCaption" href="#"><input type="checkbox" name="checkctrl" class="check-ctrl" /></th>
                                    <th><a class="tblCaption" href="#"><?php echo 'Name'; ?></a></th>
                                    <th><a class="tblCaption" href="#"><?php echo 'Username'; ?></a></th>
                                    <th><a class="tblCaption" href="#"><?php echo "Status"; ?></a></th>
                                    <th><a class="tblCaption" href="#"><?php echo 'Role'; ?></a></th>
                                    <th><a class="tblCaption" href="#"><?php echo 'Phone'; ?></a></th>
                                          <th><a class="tblCaption" href="#"><?php echo 'Gender'; ?></a></th>
                                     <th><a class="tblCaption" href="#"><?php echo 'State'; ?></a></th>
                                    <th><a class="tblCaption" href="#"><?php echo 'Lga'; ?></a></th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($this->items->fetchAll() as $item) { ?>
                                    <tr>
                                        <td><input type="checkbox" name="itemid[]" class="check-item" value="<?php echo $item->staff_id; ?>"/></td>
                                         <td><?php echo $item->surname.' '.$item->firstname; ?></td>
                                        <td><?php echo $item->staff_username; ?></td>
                                         <?php $status = ($item->status == 1) ? "Active" : "blocked"; ?>
                                        <td><?php echo $status; ?></td>
                                        <td><?php echo $item->role_name; ?></td>
                                        <td><?php echo $item->mobile; ?></td>
                                        <td><?php echo $item->sex; ?></td>
                                        <td><?php echo $item->state_name; ?></td>
                                        <td><?php echo $item->name; ?></td>
                                        <td>&nbsp;<a  href="/system/staff/edit/id/<?php echo $item->staff_id; ?>">Edit</a>&nbsp;&nbsp;<a class="removeItem" href="/system/staff/delete/id/<?php echo $item->staff_id; ?>">Delete</a>&nbsp;&nbsp;</td>
                                    </tr>
                                <?php } ?>
                            </tbody>
                        </table>
                    </form>
                <?php endif; ?>
            </div>
        </div>
    </div>
</section>


