<?php //echo $this->doctype(); ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
    <!-- include the partial  _template -->
    <head>     
        <?php 
        $this->headLink()->appendStylesheet($this->baseUrl('/vendors/twitter-bootstrap/css/bootstrap.min.css'), 'screen, projection');
        ?>

        <?php echo $this->headTitle(); ?>

        <?php echo $this->headMeta(); ?>

        <?php echo $this->headStyle(); ?>

        <?php echo $this->headLink(); ?>

        <?php echo $this->headScript(); ?>
    </head>
    <body>
        <div class="container">
            <?php $messages = $this->flashMessenger('warning', '<li class="alert alert-%s">%s</li>'); ?>
            <?php if ($messages): ?>
                <ul class="messages">
                    <?php echo $messages; ?>
                </ul> 
        <?php endif; ?>
           
           
                <?php echo $this->layout()->content; ?>
        </div>
        <div class="modalm"><!-- Place at bottom of page --></div>
    </body>
</html>
