<?php // $this->headScript()->appendFile($this->baseUrl('/js/jquery-1.7.1.min.js'));   ?>
<?php $this->headScript()->appendFile($this->baseUrl('/resources/js/permission.js')); ?>


<?php $this->title = "Role Permissions"; ?>

<div class="page-header position-relative">
    <h1>
        Define access for <strong><?php echo $this->role->role_name ?></strong> to resources.

    </h1>
</div>

<div> 
    <a id="grant-all" href="#" class="btn btn-small btn-success"><i class="icon-ok"></i> Grant Selected</a>&nbsp;&nbsp;&nbsp;
    <a id="deny-all" href="#" class="btn btn-small btn-warning"><i class="icon-remove"></i> Deny Selected</a>&nbsp;&nbsp;&nbsp;
    <a  href="/system/roles/index" class="btn btn-small btn-primary"><i class="icon-arrow-left"></i> Roles</a>
</div>
<br/>
<form id="resourceForm" method="post" action="">
    <input type="hidden" name="role" value="<?php echo $this->roleid; ?>" />
    <table  id="datatable" class="table table-striped table-bordered table-condensed">
        <thead>
            <tr>
                <th><input type="checkbox"  name="group-ctrl" class="group-id-ctrl" /></th>
                <th>Resource</th>
                <th>Access status</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($this->resources as $resource) :
                ?>
                <tr>
                    <td><input class="group-id" type="checkbox" name="resourceid[]" value="<?php echo $resource->id ?>" /></td>
                    <td>
                        <?php if ($this->access[$resource->id]): ?>

                            <h4><?php echo $resource->id ?></h4>
                        <?php else: ?>
                            <?php echo $resource->id ?>
                        <?php endif; ?>
                    </td>
                    <td>
                        <?php if ($this->access[$resource->id]): ?>
                            <span style=" display:block; height: 18px; width: 16px;   background-image: url(/resources/img/activate.png); background-repeat: none;">&nbsp;</span>
                        <?php else: ?>
                            <span style=" display:block; height: 18px; width: 16px;   background-image: url(/resources/img/block.png); background-repeat: none;">&nbsp;</span>
                        <?php endif; ?>
                    </td>
                    <td>
                        <?php if ($this->access[$resource->id]): ?>
                            <a
                                href="<?php echo $this->url(array('action' => 'deny', 'resource' => $resource->id)) ?>"
                                class="btn btn-mini btn-warning">Deny Access</a>
                            <?php else: ?>
                            <a
                                href="<?php echo $this->url(array('action' => 'grant', 'resource' => $resource->id)) ?>"
                                class="btn btn-mini btn-success">Grant Access</a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</form>
<!-- end -->
