
<style type="text/css">
    form#searchbox {
        margin: 0 0 5px 0;
        display: inline-block;

    }
    li {
        list-style-type: none;
    }
</style>
<br/>
<div class="page">  
    
   
    <div class="span7 infobox-container">
        <div class="infobox infobox-green  ">
            <div class="infobox-icon">
                <i class="icon-ambulance"></i>
            </div>

            <div class="infobox-data">
                <a class="green" href="/system/drivetrain/">  <span class="infobox-data-number">Manage</span> </a>
                <div class="infobox-content"> <a class="green" href="/system/drivetrain/">Drive trains</a></div>
            </div>
        </div>

        <div class="infobox infobox-blue  ">
            <div class="infobox-icon">
                <i class="icon-credit-card"></i>
            </div>

            <div class="infobox-data">
                <a class="blue" href="/system/chargecycles/">  <span class="infobox-data-number">Manage</span> </a>
                <div class="infobox-content"> <a class="blue" href="/system/chargecycles/">Charge cycles</a></div>
            </div>
        </div>

        <div class="infobox infobox-pink  ">
            <div class="infobox-icon">
                <i class="icon-medkit"></i>
            </div>

            <div class="infobox-data">
                <a class="pink" href="/system/carriageuses/">  <span class="infobox-data-number">Manage</span> </a>
                <div class="infobox-content"> <a class="pink" href="/system/carriageuses/">Carriage Usages</a></div>
            </div>
        </div>

        <div class="infobox infobox-red ">
            <div class="infobox-icon">
                <i class="icon-tasks"></i>
            </div>

            <div class="infobox-data">
                <a class="red" href="/system/manufacturers/">  <span class="infobox-data-number">Manage</span> </a>
                <div class="infobox-content"> <a class="red" href="/system/manufacturers/">Manufacturers</a></div>
            </div>
        </div>

        <div class="infobox infobox-brown ">
            <div class="infobox-icon">
                <i class="icon-home"></i>
            </div>

            <div class="infobox-data">
                <a class="brown" href="/system/mlos/">  <span class="infobox-data-number">Manage</span> </a>
                <div class="infobox-content"> <a class="brown" href="/system/mlos/">Mlos</a></div>
            </div>
        </div>

        <div class="infobox infobox-orange ">
            <div class="infobox-icon">
                <i class="icon-user"></i>
            </div>
            <div class="infobox-data">
                <a class="orange" href="/system/mla/">  <span class="infobox-data-number">Manage</span> </a>
                <div class="infobox-content"> <a class="orange" href="/system/mla/">Mla</a></div>
            </div>
        </div>

        <div class="infobox infobox-green  ">
            <div class="infobox-icon">
                <i class="icon-money"></i>
            </div>

            <div class="infobox-data">
                <a class="green" href="/default/charges/estimate/">  <span class="infobox-data-number">Document</span> </a>
                <div class="infobox-content"> <a class="green" href="/default/charges/estimate/">Cost calculator</a></div>
            </div>
        </div>

        <div class="infobox infobox-blue  ">
            <div class="infobox-icon">
                <i class="icon-user"></i>
            </div>

            <div class="infobox-data">
                <a class="blue" href="/system/staff/">  <span class="infobox-data-number">Manage</span> </a>
                <div class="infobox-content"> <a class="blue" href="/system/staff/">Staff</a></div>
            </div>
        </div>

        <div class="infobox infobox-pink  ">
            <div class="infobox-icon">
                <i class="icon-credit-card"></i>
            </div>

            <div class="infobox-data">
                <a class="pink" href="/default/charges/">  <span class="infobox-data-number">Manage</span> </a>
                <div class="infobox-content"> <a class="pink" href="/default/charges/">Charges</a></div>
            </div>
        </div>


        <div class="infobox infobox-red ">
            <div class="infobox-icon">
                <i class="icon-tasks"></i>
            </div>

            <div class="infobox-data">
                <a class="red" href="/system/enginetypes/">  <span class="infobox-data-number">Manage</span> </a>
                <div class="infobox-content"> <a class="red" href="/system/enginetypes/">Engine types</a></div>
            </div>
        </div>

        <div class="infobox infobox-brown ">
            <div class="infobox-icon">
                <i class="icon-tasks"></i>
            </div>

            <div class="infobox-data">
                <a class="brown" href="/system/titles/">  <span class="infobox-data-number">Manage</span> </a>
                <div class="infobox-content"> <a class="brown" href="/system/titles/">Titles</a></div>
            </div>
        </div>

        <div class="infobox infobox-orange ">
            <div class="infobox-icon">
                <i class="icon-user"></i>
            </div>
            <div class="infobox-data">
                <a class="orange" href="/system/vehicleconditions/">  <span class="infobox-data-number">Manage</span> </a>
                <div class="infobox-content"> <a class="orange" href="/system/vehicleconditions/">Vehicle conditions</a></div>
            </div>
        </div>


        <div class="infobox infobox-green  ">
            <div class="infobox-icon">
                <i class="icon-tasks"></i>
            </div>

            <div class="infobox-data">
                <a class="green" href="/system/vehicletypes/">  <span class="infobox-data-number">Manage</span> </a>
                <div class="infobox-content"> <a class="green" href="/default/charges/estimate/">Vehicle types</a></div>
            </div>
        </div>

        <div class="infobox infobox-blue  ">
            <div class="infobox-icon">
                <i class="icon-tasks"></i>
            </div>

            <div class="infobox-data">
                <a class="blue" href="/system/vehicleuses/">  <span class="infobox-data-number">Manage</span> </a>
                <div class="infobox-content"> <a class="blue" href="/system/vehicleuses/">Vehicle uses</a></div>
            </div>
        </div>

        <div class="infobox infobox-pink  ">
            <div class="infobox-icon">
                <i class="icon-tasks"></i>
            </div>

            <div class="infobox-data">
                <a class="pink" href="/system/resources/">  <span class="infobox-data-number">Manage</span> </a>
                <div class="infobox-content"> <a class="pink" href="/system/resources/">Permissions</a></div>
            </div>
        </div>

        <div class="infobox infobox-red ">
            <div class="infobox-icon">
                <i class="icon-tasks"></i>
            </div>

            <div class="infobox-data">
                <a class="pink" href="/system/roles/">  <span class="infobox-data-number">Manage</span> </a>
                <div class="infobox-content"> <a class="pink" href="/system/roles/">Roles</a></div>
            </div>

        </div>
        <div class="infobox infobox-brown ">
            <div class="infobox-icon">
                <i class="icon-tasks"></i>
            </div>

            <div class="infobox-data">
                <a class="brown" href="/system/plate/">  <span class="infobox-data-number">Manage</span> </a>
                <div class="infobox-content"> <a class="brown" href="/system/plate/">Title platenumbers</a></div>
            </div>

        </div>

        <div class="infobox infobox-red ">
            <div class="infobox-icon">
                <i class="icon-tasks"></i>
            </div>

            <div class="infobox-data">
                <a class="brown" href="/default/charges/document">  <span class="infobox-data-number">Print</span> </a>
                <div class="infobox-content"> <a class="red" href="/default/charges/document/">Document headers</a></div>
            </div>

        </div>
        
        <div class="infobox infobox-brown ">
            <div class="infobox-icon">
                <i class="icon-tasks"></i>
            </div>

            <div class="infobox-data">
                <a class="brown" href="/default/mvcard/index/">  <span class="infobox-data-number">Generate</span> </a>
                <div class="infobox-content"> <a class="brown" href="/default/mvcard/index/">Mvreg cards</a></div>
            </div>

        </div>
        <div class="space-6"></div>
    </div>
</div>



