
<div class="login-container">
    <div class="row-fluid">
        <div class="center">
            <h1>
                <i class="icon-leaf green"></i>
             <!--   <span class="red">Mvreg</span>
                <span class="white">2.0</span> -->
                  <span class="red">CARREG</span>
            </h1>
        <!--    <h4 class="blue">&copy;Rom-flex LTD 2013</h4 -->
        </div>
    </div>

    <div class="space-6"></div>

    <div class="row-fluid">
        <div class="position-relative">
            <div class="login-box visible widget-box no-border" id="login-box">
                <div class="widget-body">
                    <div class="widget-main">
                        <h4 class="header blue lighter bigger">
                            <i class="icon-coffee green"></i>
                            Staff login
                        </h4>

                        <div class="space-6"></div>

                        <form>
                            <fieldset>
                                <label>
                                    <span class="block input-icon input-icon-right">
                                         <?php   echo $this->element->user_email->renderErrors(); ?>
                                        <?php echo $this->element->user_email->renderViewHelper(); ?>
                                        <i class="icon-user"></i>
                                    </span>
                                </label>

                                <label>
                                    <span class="block input-icon input-icon-right">
                                         <?php   echo $this->element->user_password->renderErrors(); ?>
                                        <?php echo $this->element->user_password->renderViewHelper(); ?>
                                        <i class="icon-lock"></i>
                                    </span>
                                </label>

                                <div class="space"></div>

                                <div class="clearfix">
                                    <label class="inline">
                                        <input type="checkbox" class="ace">
                                        <span class="lbl"> Remember Me</span>
                                    </label>
                                      
                                       <?php echo $this->element->login->renderViewHelper(); ?>
                                   
                                </div>
                                <div class="space-4"></div>
                            </fieldset>
                        </form>
                    </div><!-- /widget-body -->
                </div><!-- /login-box -->
            </div><!-- /position-relative -->
        </div>
    </div>
    <!-- <h1>Mlo login</h1> -->
    <? //$this->loginForm; ?>
                