<?php
echo $this->doctype();
echo $this->headLink()->appendStylesheet('/css/blueprint/login.css');
echo  $this->headLink()->appendStylesheet('twit/assets/css/bootstrap.css');
      
?>
<div id="wrapper">
    <div class="slim container">	    
        <div class="row">
            <div class="six columns offset-by-five">
                <div class="login-window">
                    <div id="header" style="position: relative; border-bottom: 1px solid #ccc;">
                        <h3>Change password</h3>
                    </div>
                    <?= $this->changepass; ?>
                </div>
            </div>
        </div>
    </div>
</div>