<?php $this->headLink()->prependStylesheet('/css/config.css'); ?>
<?php $this->headScript()->appendFile($this->baseUrl('/js/jquery-1.7.1.min.js')); ?>
<?php $this->headScript()->appendFile($this->baseUrl('/twit/assets/js/bootstrap-alert.js')); ?>
<?php $this->headScript()->appendFile($this->baseUrl('/js/init_bootstrap.js')); ?>
<?php $this->headScript()->appendFile($this->baseUrl('/js/user.js')); ?>
<?php $this->headLink()->prependStylesheet('/twit/assets/css/docs.css'); ?>
<div class="subnav">
    <ul class="nav nav-pills">
        <li class=""><a href="/system/user/add" class="dropdown-toggle"><i class="icon-plus"></i>&nbsp;Add User</a></li>
      <li><a href="#badges" class="check-all"><i class="icon-check"></i>&nbsp;Check all</a></li>
      <li><a href="#typography" class="uncheck-all"><i class="icon-remove-circle icon-remove-sign"></i>&nbsp;Uncheck all</a></li>
      <li><a href="#thumbnails" class="delete-all"><i class="icon-minus"></i>&nbsp;Delete selected</a></li>
      
    </ul>
  </div>
<br/>
<form id="group-id"  action="/addressbook/delete-group/" method="post" > 
<input type="submit" id="sub-btn" value="Delete selected" class="btn" /> <br/>
<center><?php echo $this->flashMessages(); ?></center>
<form action="/system/user/delete" method="post">
<table class="table table-striped table-bordered table-condensed">
    <thead>
        <tr>
            <th></th>
            <th>Name</th>
            <th>Email</th>
            <th>Role</th>
            <th colspan="2">Action</th>
        </tr>
    </thead>
    <tbody>
      
            <? foreach ($this->users as $user): ?>
                <tr>
                    <td><input class="user-group" type="checkbox" name="id[]" value="<?php echo $user->id; ?>" /></td>
                    <td><?= $user->fullname; ?></td>
                    <td><?= $user->email; ?></td>
                    <td><?= $user->role_id; ?></td>
                    <td><a href="<?php echo $this->url(array(
                     'module' => 'system',   'controller' => 'user', action => 'edit', 'id' => $user->id), null, true) ?>"><i class="icon-edit"></i>&nbsp;Edit</a></td>
                    <td><a href="<?php echo $this->url(array('module' => 'system', 'controller' => 'user', action => 'delete', 'id' => $user->id), null, true) ?>"><i class="icon-remove"></i>&nbsp;Delete</a></td>
              
                </tr>
            <? endforeach; ?>
       
    </tbody>
</table>
</form>
<?php if ($this->users instanceof Zend_Paginator): ?>
    <?php
    echo $this->paginationControl($this->users, 'Sliding', 'mypagination.phtml');
    ?>
<?php endif; ?>
