   <h5>Fund mvreg card</h5>   
<?php echo $this->form; ?>
<script type="text/javascript">
    $(function(){
    $('body').on('click', 'a.ajax', function(e){
        e.preventDefault();

        var title = $(this).attr('title');
        var remote = $(this).attr('href');
        var scardno = $("#scardno").val();
       if(scardno == ""){
           alert("Please enter the supercard no");
       }else {
           var href = $("#scardbalance").attr('href');
           var newHref = href+'/id/'+scardno;
           remote = newHref;
        Layout.alert(title, remote, {width:'400px'});
       }
    });  

Layout = {};
    Layout.alert = function (title, content, options){
        $modalTitle = $('<b>').text(title);
        $modalDismiss = $('<span class="close" data-dismiss="modal">').html('&times;');
        $modal = $('<div class="modal">');
        $modalHeader = $('<div class="modal-header">').append($modalTitle).append($modalDismiss);
        $modalBody = $('<div class="modal-body">');//.append(content);
        $modal.append($modalHeader)
        .append($modalBody).modal({
            remote: content
        }).width(options.width)
        
        return;
}

})
</script>
